# Generated by Django 5.1.2 on 2024-10-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=155)),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField(max_length=155)),
                ('is_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='to_do_images/')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'тоже какие то данные ',
            },
        ),
    ]
